language: python
python:
  - "3.8"

script:
  - pip install -r requirements.txt
  - pip install codecov
  - python app/enviroment.py test
  - flask db init
  - flask db migrate
  - flask db upgrade
  - pytest
after_success:
  - codecov