language: python
python:
  - "3.8"

stages:
  - name: test

jobs:
  include:
    - stage: test
    script:
      - pip install -r requirements.txt
      - python --version
      - python app/enviroment.py test
      - pytest