language: python
python:
  - "3.8"

script:
  - pip install -r app/requirements/prod.txt
  - pip install -r app/requirements/test.txt
  - python app/enviroment.py test
  - flask db init
  - flask db migrate
  - flask db upgrade
  - coverage run -m pytest
  - coverage report

after_success:
  - codecov